# Generated by Django 5.0 on 2024-09-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
