# Generated by Django 5.0 on 2024-09-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
