# Generated by Django 5.0 on 2024-09-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
