# Generated by Django 5.0 on 2024-09-09 06:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
